import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';

// User table with comprehensive fields for user management
export const users = sqliteTable('users', {
  id: text('id').primaryKey().notNull(), // Mandatory id, generated by the server
  email: text('email').notNull().unique(), // Email must be unique
  hashedPassword: text('hashed_password').notNull(), // Hashed password
  displayName: text('display_name').notNull(), // Display name
  username: text('username').notNull().unique(), // Username (@ handle), must be unique
  age: integer('age'), // Nullable age
  resetKey: text('reset_key'), // Reset password key
  resetKeyExpires: text('reset_key_expires'), // Reset key expiration timestamp
  emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(), // Email verification status
  emailVerificationKey: text('email_verification_key'), // Email verification key
  emailVerificationKeyExpires: text('email_verification_key_expires'), // Email verification key expiration
  isBanned: integer('is_banned', { mode: 'boolean' }).default(false).notNull(), // Ban status
  lastPasswordReset: text('last_password_reset'), // Last password reset timestamp
  profilePictureUrl: text('profile_picture_url'), // Profile picture URL (stored in Supabase bucket)
  newEmail: text('new_email'), // New email field for email changes
  newEmailVerificationKey: text('new_email_verification_key'), // New email verification key
  newEmailVerificationKeyExpires: text('new_email_verification_key_expires'), // New email verification key expiration
  createdAt: text('created_at')
    .default(sql`CURRENT_TIMESTAMP`)
    .notNull(),
  updatedAt: text('updated_at')
    .default(sql`CURRENT_TIMESTAMP`)
    .notNull(),
});

// Sessions table to manage user sessions
export const sessions = sqliteTable('sessions', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id),
  expiresAt: integer('expires_at').notNull(),
});

// Verification tokens table - keeping for any additional verification needs
export const verificationTokens = sqliteTable('verification_tokens', {
  id: text('id').primaryKey(),
  token: text('token').notNull().unique(),
  userId: text('user_id')
    .notNull()
    .references(() => users.id),
  expiresAt: integer('expires_at').notNull(),
  createdAt: text('created_at')
    .default(sql`CURRENT_TIMESTAMP`)
    .notNull(),
});