import { pgTable, text, integer, boolean, decimal, timestamp } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// User table with comprehensive fields for user management
export const users = pgTable('users', {
  id: text('id').primaryKey().notNull(),
  email: text('email').notNull().unique(),
  hashedPassword: text('hashed_password').notNull(),
  displayName: text('display_name').notNull(),
  username: text('username').notNull().unique(),
  age: integer('age'),
  resetKey: text('reset_key'),
  resetKeyExpires: text('reset_key_expires'),
  isBanned: boolean('is_banned').default(false).notNull(),
  lastPasswordReset: text('last_password_reset'),
  profilePictureUrl: text('profile_picture_url'),
  createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
  updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
});

// Settings table - stores all accessibility and UI preferences for a user
export const settings = pgTable('settings', {
  userEmail: text('user_email').primaryKey().notNull().references(() => users.email),
  fontSize: text('font_size').default('medium'), // Changed from 'normal'
  colorTheme: text('color_theme').default('default'), // Changed from 'normal'
  darkMode: boolean('dark_mode').default(false),
  reducedMotion: boolean('reduced_motion').default(false),
  focusOutlines: boolean('focus_outlines').default(false),
  speechEnabled: boolean('speech_enabled').default(false),
  speechSpeed: text('speech_speed').default('1'), // Changed from decimal to text
  speechVolume: text('speech_volume').default('0.8'), // Changed from decimal to text
  speechInstructions: boolean('speech_instructions').default(false),
  audioFeedback: boolean('audio_feedback').default(false),
  soundEffects: boolean('sound_effects').default(false),
  readingGuide: boolean('reading_guide').default(false),
  textSpacing: text('text_spacing').default('normal'),
  lineHeight: text('line_height').default('normal'),
  wordSpacing: text('word_spacing').default('normal'),
  colorOverlay: text('color_overlay').default('none'),
  breakReminders: boolean('break_reminders').default(false),
  sensoryBreaks: boolean('sensory_breaks').default(false),
  visibleTimers: boolean('visible_timers').default(false),
  focusSessions: boolean('focus_sessions').default(false),
  distractionReduction: boolean('distraction_reduction').default(false),
  simplifiedUi: boolean('simplified_ui').default(false),
  minimalMode: boolean('minimal_mode').default(false),
  cognitiveLoad: text('cognitive_load').default('full'),
  errorHandlingStyle: text('error_handling_style').default('standard'),
  feedbackStyle: text('feedback_style').default('mixed'),
  learningStyle: text('learning_style').default('visual'),
});

// Progress table - tracks a user's completion status for all learning modules
export const progress = pgTable('progress', {
  userEmail: text('user_email').primaryKey().notNull().references(() => users.email),
  currentStreak: integer('current_streak').default(0),
  xpToday: integer('xp_today').default(0),
  dailyGoal: integer('daily_goal').default(150),
  hearts: integer('hearts').default(3),
  coins: integer('coins').default(0),
  totalXpEarned: integer('total_xp_earned').default(0),
  totalTimeSpent: integer('total_time_spent').default(0),
  progressPlacementStatus: text('progress_placement_status'),
  progressPlacementCompletedAt: timestamp('progress_placement_completed_at'),
  progressPlacementAttempts: integer('progress_placement_attempts').default(0),
  progressPlacementTimeSpent: integer('progress_placement_time_spent').default(0),
  progressIntroductionStatus: text('progress_introduction_status'),
  progressIntroductionCompletedAt: timestamp('progress_introduction_completed_at'),
  progressIntroductionAttempts: integer('progress_introduction_attempts').default(0),
  progressIntroductionTimeSpent: integer('progress_introduction_time_spent').default(0),
  progressRegressionStatus: text('progress_regression_status'),
  progressRegressionCompletedAt: timestamp('progress_regression_completed_at'),
  progressRegressionAttempts: integer('progress_regression_attempts').default(0),
  progressRegressionTimeSpent: integer('progress_regression_time_spent').default(0),
  progressClusteringStatus: text('progress_clustering_status'),
  progressClusteringCompletedAt: timestamp('progress_clustering_completed_at'),
  progressClusteringAttempts: integer('progress_clustering_attempts').default(0),
  progressClusteringTimeSpent: integer('progress_clustering_time_spent').default(0),
  progressNeuralNetworkStatus: text('progress_neural_network_status'),
  progressNeuralNetworkCompletedAt: timestamp('progress_neural_network_completed_at'),
  progressNeuralNetworkAttempts: integer('progress_neural_network_attempts').default(0),
  progressNeuralNetworkTimeSpent: integer('progress_neural_network_time_spent').default(0),
  progressTrainingLabStatus: text('progress_training_lab_status'),
  progressTrainingLabCompletedAt: timestamp('progress_training_lab_completed_at'),
  progressTrainingLabAttempts: integer('progress_training_lab_attempts').default(0),
  progressTrainingLabTimeSpent: integer('progress_training_lab_time_spent').default(0),
  progressPracticeStatus: text('progress_practice_status'),
  progressPracticeCompletedAt: timestamp('progress_practice_completed_at'),
  progressPracticeAttempts: integer('progress_practice_attempts').default(0),
  progressPracticeTimeSpent: integer('progress_practice_time_spent').default(0),
  progressAccessibilityDemoStatus: text('progress_accessibility_demo_status'),
  progressAccessibilityDemoCompletedAt: timestamp('progress_accessibility_demo_completed_at'),
  progressAccessibilityDemoAttempts: integer('progress_accessibility_demo_attempts').default(0),
  progressAccessibilityDemoTimeSpent: integer('progress_accessibility_demo_time_spent').default(0),
});

// Grades table
export const grades = pgTable('grades', {
  userEmail: text('user_email').primaryKey().notNull().references(() => users.email),
  gradePlacementTestScore: decimal('grade_placement_test_score'),
  gradePlacementTestRecordedAt: timestamp('grade_placement_test_recorded_at'),
  gradePlacementTestAttempts: integer('grade_placement_test_attempts').default(0),
  gradeIntroductionQuizScore: decimal('grade_introduction_quiz_score'),
  gradeIntroductionQuizRecordedAt: timestamp('grade_introduction_quiz_recorded_at'),
  gradeRegressionGameScore: decimal('grade_regression_game_score'),
  gradeRegressionGameRecordedAt: timestamp('grade_regression_game_recorded_at'),
  gradeRegressionGameAttempts: integer('grade_regression_game_attempts').default(0),
  gradeRegressionGameTimeSpent: integer('grade_regression_game_time_spent').default(0),
  gradeClusteringGameScore: decimal('grade_clustering_game_score'),
  gradeClusteringGameRecordedAt: timestamp('grade_clustering_game_recorded_at'),
  gradeClusteringGameAttempts: integer('grade_clustering_game_attempts').default(0),
  gradeClusteringGameTimeSpent: integer('grade_clustering_game_time_spent').default(0),
  gradeNeuralNetworkAccuracy: decimal('grade_neural_network_accuracy'),
  gradeNeuralNetworkRecordedAt: timestamp('grade_neural_network_recorded_at'),
  gradeTrainingLabAccuracy: decimal('grade_training_lab_accuracy'),
  gradeTrainingLabRecordedAt: timestamp('grade_training_lab_recorded_at'),
  gradeTrainingLabAttempts: integer('grade_training_lab_attempts').default(0),
  gradePracticeModeScore: decimal('grade_practice_mode_score'),
  gradePracticeModeRecordedAt: timestamp('grade_practice_mode_recorded_at'),
  gradePracticeModeAttempts: integer('grade_practice_mode_attempts').default(0),
  gradePracticeModeTimeSpent: integer('grade_practice_mode_time_spent').default(0),
});

// Achievements table
export const achievements = pgTable('achievements', {
  userEmail: text('user_email').primaryKey().notNull().references(() => users.email),
  achievementFirstStepsUnlocked: boolean('achievement_first_steps_unlocked'),
  achievementFirstStepsUnlockedAt: timestamp('achievement_first_steps_unlocked_at'),
  achievementHighScoreUnlocked: boolean('achievement_high_score_unlocked'),
  achievementHighScoreUnlockedAt: timestamp('achievement_high_score_unlocked_at'),
  achievement7DayStreakUnlocked: boolean('achievement_7_day_streak_unlocked'),
  achievement7DayStreakUnlockedAt: timestamp('achievement_7_day_streak_unlocked_at'),
  achievementAllModulesCompletedUnlocked: boolean('achievement_all_modules_completed_unlocked'),
  achievementAllModulesCompletedUnlockedAt: timestamp('achievement_all_modules_completed_unlocked_at'),
  achievementPracticeMasterUnlocked: boolean('achievement_practice_master_unlocked'),
  achievementPracticeMasterUnlockedAt: timestamp('achievement_practice_master_unlocked_at'),
  totalAchievementsUnlocked: integer('total_achievements_unlocked').default(0),
});